import { useCallback, useState } from 'react'
import { addAttractionImage, deleteAttractionImage, setPrimaryAttractionImage } from '../../api/attractions'
import ConfirmationModal from '../ConfirmationModal'
import AttractionPreviewModal from './AttractionPreviewModal'
import { apiErrorMessage } from '../../pages/attractions/attractionUtils'

export default function AttractionImageManager({ attraction, onUpdated }) {
  const [urls, setUrls] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [confirming, setConfirming] = useState(null); const [previewOpen, setPreviewOpen] = useState(false)
  const images = attraction.images || []
  const primary = images.find((image) => image.isPrimary) || images.find((image) => image.imageUrl)
  const refresh = useCallback(async () => { await onUpdated() }, [onUpdated])
  async function addImages(event) { event.preventDefault(); const values = urls.split(/\r?\n|,/).map((value) => value.trim()).filter(Boolean); if (!values.length) { setError('Add at least one image URL.'); return } setSaving(true); setError(''); setNotice(''); try { for (const imageUrl of values) await addAttractionImage(attraction.id, { imageUrl, altText: attraction.name, sortOrder: images.length }); setUrls(''); setNotice(`${values.length} image${values.length === 1 ? '' : 's'} added successfully.`); await refresh() } catch (requestError) { setError(apiErrorMessage(requestError, 'Unable to add image. Use a valid image URL.')) } finally { setSaving(false) } }
  async function removeImage() { const image = confirming; setSaving(true); setError(''); try { await deleteAttractionImage(attraction.id, image.id); setConfirming(null); setNotice('Image removed successfully.'); await refresh() } catch (requestError) { setError(apiErrorMessage(requestError, 'Unable to remove image.')); setConfirming(null) } finally { setSaving(false) } }
  async function setPrimary(image) { setSaving(true); setError(''); try { await setPrimaryAttractionImage(attraction.id, image.id); setNotice('Main display image updated.'); await refresh() } catch (requestError) { setError(apiErrorMessage(requestError, 'Unable to update the main image.')) } finally { setSaving(false) } }
  return <section className="image-manager form-section"><div className="form-section-heading"><p className="eyebrow">Attraction images</p><h2>Manage your visual presentation</h2><p className="muted">Add image URLs, choose one main image, and preview how this attraction appears.</p></div>{notice && <p className="success-message" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}<form className="image-add-form" onSubmit={addImages}><label htmlFor="attraction-image-urls">Image URL(s)<textarea id="attraction-image-urls" rows="3" value={urls} onChange={(event) => setUrls(event.target.value)} placeholder="Paste one or more image URLs, one per line" /></label><button className="button button-secondary-light" type="submit" disabled={saving}>+ Add images</button></form>{images.length ? <div className="image-management-grid">{images.map((image) => <article className="image-management-card" key={image.id}><button className="managed-image-preview" type="button" onClick={() => setPreviewOpen(true)} aria-label={`Preview ${attraction.name}`}><img src={image.imageUrl} alt={image.altText || attraction.name} /></button>{(image.isPrimary || (!images.some((item) => item.isPrimary) && image.id === primary?.id)) && <span className="main-image-badge">Main image</span>}<div className="image-management-actions">{image.isPrimary ? <span className="image-main-note">Current main image</span> : <button className="text-button" type="button" onClick={() => setPrimary(image)} disabled={saving}>Set as main</button>}<button className="text-button danger-text" type="button" onClick={() => setConfirming(image)} disabled={saving}>Remove</button></div></article>)}</div> : <div className="state-empty"><strong>No attraction images yet.</strong><span>Add image references above to build the gallery.</span></div>}{confirming && <ConfirmationModal title="Remove this image?" message="This image will no longer be associated with the attraction." confirmLabel="Remove image" isLoading={saving} onConfirm={removeImage} onClose={() => setConfirming(null)} />}{previewOpen && <AttractionPreviewModal attraction={attraction} onClose={() => setPreviewOpen(false)} canEdit={false} />}</section>
}
