import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAttractionById, getAvailability } from '../../api/attractions'
import { apiErrorMessage, timeValue } from './attractionUtils'

function readableDate(value) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) }

export default function AttractionAvailabilityPage() {
  const { id } = useParams(); const [attraction, setAttraction] = useState(null); const [date, setDate] = useState(''); const [availability, setAvailability] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getAttractionById(id), getAvailability(id)]).then(([item, data]) => { setAttraction(item); setAvailability(data) }).catch((e) => setError(apiErrorMessage(e, 'Unable to load availability.'))).finally(() => setLoading(false)) }, [id])
  async function filter(event) { event.preventDefault(); setLoading(true); setError(''); try { setAvailability(await getAvailability(id, date || undefined)) } catch (e) { setError(apiErrorMessage(e, 'Unable to refresh availability.')) } finally { setLoading(false) } }
  if (loading && !availability) return <section className="page-section"><div className="state-card" role="status"><strong>Loading availability…</strong><span>Preparing the capacity overview.</span></div></section>
  return <section className="page-section wide-page operations-page"><Link className="back-link" to={`/provider/attractions/${id}/edit`}>← {attraction?.name || 'Attraction'}</Link><div className="consistent-page-header"><p className="eyebrow">Provider workspace · Operations view</p><h1>Availability</h1><p className="lead">Review session capacity for {attraction?.name || 'this attraction'}.</p></div>{error && <p className="form-error notice-error" role="alert">{error}</p>}<form className="availability-toolbar" onSubmit={filter}><label htmlFor="availability-date">Filter by date<input id="availability-date" type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><button className="button button-primary" disabled={loading}>{loading ? 'Refreshing…' : 'Refresh availability'}</button></form>{!availability?.slots?.length ? <div className="empty-state"><h2>No availability is currently available.</h2><p>No experience slots are available for the selected date.</p></div> : <div className="availability-grid">{availability.slots.map((slot) => { const ratio = slot.capacity ? slot.availableCapacity / slot.capacity : 0; const label = slot.availableCapacity === 0 ? 'Full' : ratio <= 0.25 ? 'Low availability' : 'Available'; return <article className="availability-card" key={slot.id}><div className="availability-heading"><div><p className="eyebrow">Session date</p><strong>{readableDate(slot.date)}</strong></div><span className={`availability-label availability-${label.toLowerCase().replace(' ', '-')}`}>{label}</span></div><p className="availability-time">{timeValue(slot.startTime)} – {timeValue(slot.endTime)}</p><div className="capacity-bar"><span style={{ width: `${Math.max(0, Math.min(100, ratio * 100))}%` }} /></div><div className="availability-capacity"><span><small>Available</small><strong>{slot.availableCapacity}</strong></span><span><small>Total capacity</small><strong>{slot.capacity}</strong></span></div></article> })}</div>}</section>
}
