import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAttractionById, getAvailability } from '../../api/attractions'
import { apiErrorMessage, timeValue } from './attractionUtils'

export default function AttractionAvailabilityPage() {
  const { id } = useParams(); const [attraction, setAttraction] = useState(null); const [date, setDate] = useState(''); const [availability, setAvailability] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getAttractionById(id), getAvailability(id)]).then(([item, data]) => { setAttraction(item); setAvailability(data) }).catch((e) => setError(apiErrorMessage(e, 'Unable to load availability.'))).finally(() => setLoading(false)) }, [id])
  async function filter(event) { event.preventDefault(); setLoading(true); setError(''); try { setAvailability(await getAvailability(id, date || undefined)) } catch (e) { setError(apiErrorMessage(e)) } finally { setLoading(false) } }
  if (loading && !availability) return <section className="page-section"><p className="notice">Loading availability…</p></section>
  return <section className="page-section wide-page"><Link className="back-link" to={`/provider/attractions/${id}/edit`}>← {attraction?.name || 'Attraction'}</Link><p className="eyebrow">Operations view</p><h1>Availability</h1><p className="lead">Review session capacity for this attraction.</p>{error && <p className="form-error notice-error" role="alert">{error}</p>}<form className="date-filter" onSubmit={filter}><label htmlFor="availability-date">Filter by date</label><input id="availability-date" type="date" value={date} onChange={(e) => setDate(e.target.value)} /><button className="button button-primary" disabled={loading}>Refresh</button></form>{!availability?.slots?.length ? <div className="empty-state"><h2>No availability data</h2><p>No experience slots are available for the selected date.</p></div> : <div className="availability-grid">{availability.slots.map((slot) => { const ratio = slot.capacity ? slot.availableCapacity / slot.capacity : 0; const label = slot.availableCapacity === 0 ? 'Full' : ratio <= 0.25 ? 'Low availability' : 'Available'; return <article className="availability-card" key={slot.id}><div className="availability-heading"><strong>{slot.date}</strong><span className={`availability-label availability-${label.toLowerCase().replace(' ', '-')}`}>{label}</span></div><p>{timeValue(slot.startTime)} – {timeValue(slot.endTime)}</p><div className="capacity-bar"><span style={{ width: `${Math.max(0, Math.min(100, ratio * 100))}%` }} /></div><strong>{slot.availableCapacity} of {slot.capacity} places available</strong></article> })}</div>}</section>
}
