import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { createSchedule, deleteSchedule, getAttractionById, updateSchedule } from '../../api/attractions'
import ScheduleForm from '../../components/attractions/ScheduleForm'
import { apiErrorMessage, timeValue } from './attractionUtils'
import ConfirmationModal from '../../components/ConfirmationModal'

export default function AttractionSchedulesPage() {
  const { id } = useParams(); const [attraction, setAttraction] = useState(null); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [confirming, setConfirming] = useState(null); const [deleting, setDeleting] = useState(false)
  const load = useCallback(async () => { try { setAttraction(await getAttractionById(id)) } catch (e) { setError(apiErrorMessage(e, 'Unable to load schedules.')) } finally { setLoading(false) } }, [id])
  useEffect(() => { load() }, [load])
  function initial(schedule) { return { dayOfWeek: schedule.dayOfWeek, openingTime: timeValue(schedule.openingTime), closingTime: timeValue(schedule.closingTime), isClosed: schedule.isClosed } }
  async function save(data) { setSaving(true); setError(''); try { if (editing) await updateSchedule(id, editing.id, data); else await createSchedule(id, data); setEditing(null); setMessage(editing ? 'Schedule updated successfully.' : 'Schedule created successfully.'); await load() } catch (e) { setError(apiErrorMessage(e, 'Unable to save schedule.')) } finally { setSaving(false) } }
  async function remove(schedule) { setDeleting(true); try { await deleteSchedule(id, schedule.id); setConfirming(null); setMessage('Schedule deleted successfully.'); await load() } catch (e) { setError(apiErrorMessage(e, 'Unable to delete schedule.')); setConfirming(null) } finally { setDeleting(false) } }
  if (loading) return <section className="page-section"><div className="state-card" role="status"><strong>Loading schedules…</strong><span>Preparing the opening-hours workspace.</span></div></section>
  return <section className="page-section wide-page operations-page"><Link className="back-link" to={`/provider/attractions/${id}/edit`}>← {attraction?.name || 'Attraction'}</Link><div className="consistent-page-header"><p className="eyebrow">Provider workspace · Opening hours</p><h1>Schedules</h1><p className="lead">Keep the provider schedule accurate for visitors and operations.</p></div>{message && <p className="success-message" role="status">{message}</p>}{error && <p className="form-error notice-error" role="alert">{error}</p>}<section className="panel operations-form-panel"><div className="section-heading"><div><p className="eyebrow">{editing ? 'Update schedule' : 'Add schedule'}</p><h2>{editing ? 'Edit opening hours' : 'Set opening hours'}</h2></div>{editing && <button className="button button-secondary-light" type="button" onClick={() => setEditing(null)}>Cancel edit</button>}</div><ScheduleForm key={editing?.id || 'new'} initialValues={editing ? initial(editing) : undefined} onSubmit={save} onCancel={editing ? () => setEditing(null) : null} isSubmitting={saving} serverError={error} /></section><section className="list-panel operations-list-panel"><div className="section-heading"><div><p className="eyebrow">Configured hours</p><h2>Existing schedules</h2></div><span className="record-count">{attraction?.schedules?.length || 0} days</span></div>{!attraction?.schedules?.length ? <div className="state-empty"><strong>No schedules have been added.</strong><span>Add opening hours above to make this attraction easier to plan.</span></div> : attraction.schedules.map((schedule) => <div className="operation-row" key={schedule.id}><div className="operation-row-main"><strong>{schedule.dayOfWeek}</strong><span>{schedule.isClosed ? 'Closed' : `${timeValue(schedule.openingTime)} – ${timeValue(schedule.closingTime)}`}</span></div><div className="row-actions"><button className="text-button" type="button" onClick={() => setEditing(schedule)}>Edit</button><button className="text-button danger-text" type="button" onClick={() => setConfirming(schedule)}>Delete</button></div></div>)}</section>{confirming && <ConfirmationModal title="Remove this schedule?" message={`${confirming.dayOfWeek} · ${confirming.isClosed ? 'Closed' : `${timeValue(confirming.openingTime)} – ${timeValue(confirming.closingTime)}`}. Removing it will delete this opening-hours entry.`} confirmLabel="Remove schedule" isLoading={deleting} onConfirm={() => remove(confirming)} onClose={() => setConfirming(null)} />}</section>
}
