import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { approveAttraction, getAttractionById } from '../../api/attractions'
import StatusBadge from '../../components/attractions/StatusBadge'
import { apiErrorMessage, timeValue } from '../attractions/attractionUtils'

function DetailSection({ label, children }) { return <section className="review-section"><p className="eyebrow">{label}</p>{children}</section> }

export default function AdminAttractionDetailsPage() {
  const { id } = useParams(); const [attraction, setAttraction] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { getAttractionById(id).then(setAttraction).catch((e) => setError(apiErrorMessage(e, 'Unable to load attraction.'))).finally(() => setLoading(false)) }, [id])
  async function approve() { setSaving(true); setError(''); try { setAttraction(await approveAttraction(id)); setMessage('Attraction approved successfully.') } catch (e) { setError(apiErrorMessage(e, 'Unable to approve attraction.')) } finally { setSaving(false) } }
  if (loading) return <section className="page-section"><div className="state-card" role="status"><strong>Loading attraction…</strong><span>Preparing the review details.</span></div></section>
  if (error && !attraction) return <section className="page-section"><div className="state-card state-error" role="alert"><strong>{error}</strong><span>We could not load this attraction.</span></div><Link className="button button-secondary-light" to="/admin/attractions">Back to pending attractions</Link></section>
  return <section className="page-section wide-page review-page"><Link className="back-link" to="/admin/attractions">← Pending attractions</Link><div className="page-header consistent-page-header"><div><p className="eyebrow">Administrator review</p><h1>{attraction.name}</h1><p className="lead">Inspect this provider submission before making it publicly discoverable.</p></div><StatusBadge status={attraction.status} isActive={attraction.isActive} /></div>{message && <p className="success-message" role="status">{message}</p>}{error && <p className="form-error notice-error" role="alert">{error}</p>}<div className="review-card"><DetailSection label="Attraction information"><div className="review-facts"><div><span>Name</span><strong>{attraction.name}</strong></div><div><span>Category</span><strong>{attraction.category?.name || 'Uncategorised'}</strong></div><div className="review-fact-wide"><span>Description</span><strong>{attraction.description}</strong></div></div></DetailSection><DetailSection label="Location and pricing"><div className="review-facts"><div><span>District</span><strong>{attraction.district}</strong></div><div><span>Address</span><strong>{attraction.address}</strong></div><div><span>Price</span><strong>LKR {attraction.price}</strong></div><div><span>Provider ID</span><strong>{attraction.providerId}</strong></div></div></DetailSection><DetailSection label="Schedule and availability"><div className="review-operational-list">{attraction.schedules?.length ? attraction.schedules.map((schedule) => <div key={schedule.id}><strong>{schedule.dayOfWeek}</strong><span>{schedule.isClosed ? 'Closed' : `${timeValue(schedule.openingTime)} – ${timeValue(schedule.closingTime)}`}</span></div>) : <p className="muted">No opening schedules provided.</p>}{attraction.experienceSlots?.length ? attraction.experienceSlots.slice(0, 4).map((slot) => <div key={slot.id}><strong>{slot.date}</strong><span>{timeValue(slot.startTime)} – {timeValue(slot.endTime)} · {slot.availableCapacity} of {slot.capacity} available</span></div>) : <p className="muted">No experience slots provided.</p>}</div></DetailSection><div className="review-decision"><div><p className="eyebrow">Decision</p><h2>Approval status</h2><p>Approved attractions become available through the public attraction discovery flow.</p></div>{attraction.status === 'PendingApproval' && attraction.isActive && <button className="button button-primary" type="button" onClick={approve} disabled={saving}>{saving ? 'Approving…' : 'Approve attraction'}</button>}</div></div></section>
}
