import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { approveAttraction, getPendingAttractions } from '../../api/attractions'
import StatusBadge from '../../components/attractions/StatusBadge'
import { apiErrorMessage } from '../attractions/attractionUtils'

export default function PendingAttractionsPage() {
  const [result, setResult] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [actionId, setActionId] = useState(''); const [message, setMessage] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setResult(await getPendingAttractions({ page: 1, pageSize: 100 })) } catch (e) { setError(apiErrorMessage(e, 'Unable to load pending attractions.')) } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  async function approve(attraction) { setActionId(attraction.id); setError(''); try { await approveAttraction(attraction.id); setMessage(`“${attraction.name}” was approved successfully.`); await load() } catch (e) { setError(apiErrorMessage(e, 'Unable to approve this attraction.')) } finally { setActionId('') } }
  return <section className="page-section wide-page"><div className="page-header"><div><p className="eyebrow">Administration</p><h1>Pending attractions</h1><p className="lead">Review provider submissions before they become publicly available.</p></div><Link className="button button-secondary dark-button" to="/administrator">Dashboard</Link></div>{message && <p className="success-message" role="status">{message}</p>}{loading && <p className="notice">Loading pending attractions…</p>}{error && <p className="form-error notice-error" role="alert">{error}</p>}{!loading && !error && !result?.items?.length && <div className="empty-state"><h2>No pending attractions</h2><p>All current provider submissions have been reviewed.</p></div>}<div className="management-grid">{result?.items?.map((attraction) => <article className="management-card" key={attraction.id}><div className="card-heading"><div><p className="eyebrow">{attraction.category?.name || 'Uncategorised'}</p><h2>{attraction.name}</h2></div><StatusBadge status={attraction.status} isActive={attraction.isActive} /></div><div className="card-meta"><span>{attraction.district}</span><span>Price {attraction.price}</span><span>Submitted {new Date(attraction.createdAt).toLocaleDateString()}</span></div><p className="card-description">{attraction.description}</p><p className="muted">Provider ID: {attraction.providerId}</p><div className="card-actions"><Link className="button button-secondary dark-button" to={`/admin/attractions/${attraction.id}`}>Inspect</Link><button className="button button-primary" type="button" disabled={actionId === attraction.id} onClick={() => approve(attraction)}>{actionId === attraction.id ? 'Approving…' : 'Approve'}</button></div></article>)}</div></section>
}
