import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { approveAttraction, getPendingAttractions } from '../../api/attractions'
import StatusBadge from '../../components/attractions/StatusBadge'
import { apiErrorMessage } from '../attractions/attractionUtils'

function formatDate(value) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) }

export default function PendingAttractionsPage() {
  const [result, setResult] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [actionId, setActionId] = useState(''); const [message, setMessage] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setResult(await getPendingAttractions({ page: 1, pageSize: 100 })) } catch (e) { setError(apiErrorMessage(e, 'Unable to load pending attractions.')) } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  async function approve(attraction) { setActionId(attraction.id); setError(''); try { await approveAttraction(attraction.id); setMessage(`“${attraction.name}” was approved successfully.`); await load() } catch (e) { setError(apiErrorMessage(e, 'Unable to approve this attraction.')) } finally { setActionId('') } }
  const attractions = result?.items || []
  return <section className="page-section wide-page admin-attractions-page"><div className="page-header consistent-page-header"><div><p className="eyebrow">Administrator workspace</p><h1>Pending attractions</h1><p className="lead">Review provider submissions before they become publicly available.</p></div><Link className="button button-secondary-light" to="/administrator">Back to dashboard</Link></div>{message && <p className="success-message" role="status">{message}</p>}{loading && <div className="state-card" role="status"><strong>Loading pending attractions…</strong><span>Preparing the review queue.</span></div>}{error && <p className="form-error notice-error" role="alert">{error}</p>}{!loading && !error && !attractions.length && <div className="empty-state"><h2>No pending attractions require approval.</h2><p>All current provider submissions have been reviewed.</p></div>}{!loading && !error && attractions.length > 0 && <div className="admin-attraction-list">{attractions.map((attraction) => { const image = attraction.images?.find((item) => item?.imageUrl); return <article className="admin-attraction-row" key={attraction.id}><div className="admin-attraction-thumb">{image ? <img src={image.imageUrl} alt={image.altText || attraction.name} /> : <span aria-hidden="true">✦</span>}</div><div className="admin-attraction-copy"><div className="admin-attraction-title"><div><p className="eyebrow">{attraction.category?.name || 'Uncategorised'}</p><h2>{attraction.name}</h2></div><StatusBadge status={attraction.status} isActive={attraction.isActive} /></div><p className="admin-attraction-meta">{attraction.district} · Price {attraction.price} · Submitted {formatDate(attraction.createdAt)}</p><p className="admin-attraction-provider">Provider: {attraction.providerId}</p></div><div className="admin-attraction-actions"><Link className="button button-secondary-light" to={`/admin/attractions/${attraction.id}`}>Review</Link><button className="button button-primary" type="button" disabled={actionId === attraction.id} onClick={() => approve(attraction)}>{actionId === attraction.id ? 'Approving…' : 'Approve'}</button></div></article> })}</div>}</section>
}
