// <auto-generated />
using System;
using CeylonTrail.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CeylonTrail.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CeylonTrail.Api.Models.Booking", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<Guid>("TouristId").HasColumnType("uuid");
                b.Property<Guid?>("TripId").HasColumnType("uuid");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("Status");
                b.HasIndex("TouristId");
                b.ToTable("Bookings");
            });

            modelBuilder.Entity("CeylonTrail.Api.Models.BookingItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("AttractionId").HasColumnType("uuid");
                b.Property<Guid>("BookingId").HasColumnType("uuid");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<decimal>("Subtotal").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<decimal>("UnitPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.HasKey("Id");
                b.HasIndex("BookingId");
                b.ToTable("BookingItems");
            });

            modelBuilder.Entity("CeylonTrail.Api.Models.BookingStatusHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("BookingId").HasColumnType("uuid");
                b.Property<DateTime>("ChangedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("ChangedBy").HasColumnType("uuid");
                b.Property<string>("NewStatus").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<string>("PreviousStatus").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<string>("Reason").HasMaxLength(500).HasColumnType("character varying(500)");
                b.HasKey("Id");
                b.HasIndex("BookingId");
                b.ToTable("BookingStatusHistories");
            });

            modelBuilder.Entity("CeylonTrail.Api.Models.Cancellation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("BookingId").HasColumnType("uuid");
                b.Property<DateTime>("CancelledAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("CancelledBy").HasColumnType("uuid");
                b.Property<string>("Reason").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.HasKey("Id");
                b.HasIndex("BookingId").IsUnique();
                b.ToTable("Cancellations");
            });

            modelBuilder.Entity("CeylonTrail.Api.Models.TravelAlert", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("AlertType").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("CreatedByUserId").HasColumnType("uuid");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<string>("District").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime>("EndDateTime").HasColumnType("timestamp with time zone");
                b.Property<string>("Severity").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("Source").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTime>("StartDateTime").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("CreatedByUserId");
                b.HasIndex("Status", "StartDateTime");
                b.HasIndex("District", "Status", "StartDateTime");
                b.ToTable("TravelAlerts");
            });

            modelBuilder.Entity("CeylonTrail.Api.Models.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("Role").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("CeylonTrail.Api.Models.Booking", b =>
            {
                b.HasOne("CeylonTrail.Api.Models.User", "Tourist").WithMany().HasForeignKey("TouristId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Tourist");
                b.Navigation("Cancellation");
                b.Navigation("Items");
                b.Navigation("StatusHistory");
            });
            modelBuilder.Entity("CeylonTrail.Api.Models.BookingItem", b =>
            {
                b.HasOne("CeylonTrail.Api.Models.Booking", "Booking").WithMany("Items").HasForeignKey("BookingId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Booking");
            });
            modelBuilder.Entity("CeylonTrail.Api.Models.BookingStatusHistory", b =>
            {
                b.HasOne("CeylonTrail.Api.Models.Booking", "Booking").WithMany("StatusHistory").HasForeignKey("BookingId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Booking");
            });
            modelBuilder.Entity("CeylonTrail.Api.Models.Cancellation", b =>
            {
                b.HasOne("CeylonTrail.Api.Models.Booking", "Booking").WithOne("Cancellation").HasForeignKey("CeylonTrail.Api.Models.Cancellation", "BookingId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Booking");
            });
            modelBuilder.Entity("CeylonTrail.Api.Models.TravelAlert", b =>
            {
                b.HasOne("CeylonTrail.Api.Models.User", "CreatedByUser").WithMany().HasForeignKey("CreatedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("CreatedByUser");
            });
#pragma warning restore 612, 618
        }
    }
}
